#ifndef __PRINTTYPES_H__
#define __PRINTTYPES_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintWrappers_Matrix6d(const char *paramName, const asn1SccWrappers_Matrix6d *pData);
void PrintT_UInt64(const char *paramName, const asn1SccT_UInt64 *pData);
void PrintBase_samples_Wrench(const char *paramName, const asn1SccBase_samples_Wrench *pData);
void PrintGeometry_msgs_Point32(const char *paramName, const asn1SccGeometry_msgs_Point32 *pData);
void PrintT_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintBase_samples_RigidBodyState_m(const char *paramName, const asn1SccBase_samples_RigidBodyState_m *pData);
void PrintBase_samples_frame_FramePair(const char *paramName, const asn1SccBase_samples_frame_FramePair *pData);
void PrintBase_TransformWithCovariance_m(const char *paramName, const asn1SccBase_TransformWithCovariance_m *pData);
void PrintWrappers_Vector2d(const char *paramName, const asn1SccWrappers_Vector2d *pData);
void PrintBase_samples_SonarScan(const char *paramName, const asn1SccBase_samples_SonarScan *pData);
void PrintBase_NamedVector_base_JointTransform_m(const char *paramName, const asn1SccBase_NamedVector_base_JointTransform_m *pData);
void PrintBase_samples_frame_Frame(const char *paramName, const asn1SccBase_samples_frame_Frame *pData);
void PrintGeometry_msgs_Point(const char *paramName, const asn1SccGeometry_msgs_Point *pData);
void PrintT_UInt16(const char *paramName, const asn1SccT_UInt16 *pData);
void PrintT_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintBase_JointLimits(const char *paramName, const asn1SccBase_JointLimits *pData);
void PrintBase_samples_Pointcloud(const char *paramName, const asn1SccBase_samples_Pointcloud *pData);
void PrintT_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintBase_samples_frame_frame_size_t(const char *paramName, const asn1SccBase_samples_frame_frame_size_t *pData);
void PrintBase_Pose2D_m(const char *paramName, const asn1SccBase_Pose2D_m *pData);
void PrintBase_commands_Joints(const char *paramName, const asn1SccBase_commands_Joints *pData);
void PrintBase_samples_Wrenches_m(const char *paramName, const asn1SccBase_samples_Wrenches_m *pData);
void PrintBase_samples_DepthMap_DEPTH_MEASUREMENT_STATE(const char *paramName, const asn1SccBase_samples_DepthMap_DEPTH_MEASUREMENT_STATE *pData);
void PrintBase_NamedVector_Base_JointLimitRange(const char *paramName, const asn1SccBase_NamedVector_Base_JointLimitRange *pData);
void PrintBase_Temperature(const char *paramName, const asn1SccBase_Temperature *pData);
void PrintBase_samples_Wrenches(const char *paramName, const asn1SccBase_samples_Wrenches *pData);
void PrintBase_Wrench(const char *paramName, const asn1SccBase_Wrench *pData);
void PrintBase_samples_frame_frame_attrib_t(const char *paramName, const asn1SccBase_samples_frame_frame_attrib_t *pData);
void PrintWrappers_Matrix3d(const char *paramName, const asn1SccWrappers_Matrix3d *pData);
void PrintBase_samples_BodyState_m(const char *paramName, const asn1SccBase_samples_BodyState_m *pData);
void PrintT_Int64(const char *paramName, const asn1SccT_Int64 *pData);
void PrintBase_JointTransformVector_m(const char *paramName, const asn1SccBase_JointTransformVector_m *pData);
void PrintBase_samples_SonarBeam(const char *paramName, const asn1SccBase_samples_SonarBeam *pData);
void PrintBase_samples_LaserScan(const char *paramName, const asn1SccBase_samples_LaserScan *pData);
void PrintBase_Wrench_m(const char *paramName, const asn1SccBase_Wrench_m *pData);
void PrintBase_JointTransform_m(const char *paramName, const asn1SccBase_JointTransform_m *pData);
void PrintBase_NamedVector_Base_Wrench(const char *paramName, const asn1SccBase_NamedVector_Base_Wrench *pData);
void PrintBase_samples_RigidBodyAcceleration(const char *paramName, const asn1SccBase_samples_RigidBodyAcceleration *pData);
void PrintBase_Time_Resolution(const char *paramName, const asn1SccBase_Time_Resolution *pData);
void PrintT_Double(const char *paramName, const asn1SccT_Double *pData);
void PrintBase_TimeStamped_Base_commands_Motion2D(const char *paramName, const asn1SccBase_TimeStamped_Base_commands_Motion2D *pData);
void PrintWrappers_Quaterniond(const char *paramName, const asn1SccWrappers_Quaterniond *pData);
void PrintBase_commands_Speed6D(const char *paramName, const asn1SccBase_commands_Speed6D *pData);
void PrintBase_NamedVector_Base_JointTrajectory(const char *paramName, const asn1SccBase_NamedVector_Base_JointTrajectory *pData);
void PrintStd_orogen_typekits_mtype_std_vector_base_JointTransform(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_JointTransform *pData);
void PrintT_String(const char *paramName, const asn1SccT_String *pData);
void PrintBase_Waypoint_m(const char *paramName, const asn1SccBase_Waypoint_m *pData);
void PrintBase_TwistWithCovariance(const char *paramName, const asn1SccBase_TwistWithCovariance *pData);
void PrintWrappers_Matrix2d(const char *paramName, const asn1SccWrappers_Matrix2d *pData);
void PrintBase_NamedVector_base_Wrench_m(const char *paramName, const asn1SccBase_NamedVector_base_Wrench_m *pData);
void PrintBase_samples_Motion2D(const char *paramName, const asn1SccBase_samples_Motion2D *pData);
void PrintWrappers_geometry_SplineType(const char *paramName, const asn1SccWrappers_geometry_SplineType *pData);
void PrintBase_Pose_m(const char *paramName, const asn1SccBase_Pose_m *pData);
void PrintBase_samples_RigidBodyAcceleration_m(const char *paramName, const asn1SccBase_samples_RigidBodyAcceleration_m *pData);
void PrintBase_Pressure(const char *paramName, const asn1SccBase_Pressure *pData);
void PrintStd_vector_Wrappers_Vector4d(const char *paramName, const asn1SccStd_vector_Wrappers_Vector4d *pData);
void PrintBase_JointLimitRange(const char *paramName, const asn1SccBase_JointLimitRange *pData);
void PrintBase_samples_DepthMap_UNIT_AXIS(const char *paramName, const asn1SccBase_samples_DepthMap_UNIT_AXIS *pData);
void PrintBase_samples_Pressure(const char *paramName, const asn1SccBase_samples_Pressure *pData);
void PrintBase_PoseUpdateThreshold(const char *paramName, const asn1SccBase_PoseUpdateThreshold *pData);
void PrintStd_orogen_typekits_mtype_std_vector_base_Wrench(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_Wrench *pData);
void PrintBase_JointTransformVector(const char *paramName, const asn1SccBase_JointTransformVector *pData);
void PrintBase_Angle(const char *paramName, const asn1SccBase_Angle *pData);
void PrintT_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintStd_orogen_typekits_mtype_std_vector_base_Waypoint(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_Waypoint *pData);
void PrintT_Int16(const char *paramName, const asn1SccT_Int16 *pData);
void PrintT_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintBase_JointState(const char *paramName, const asn1SccBase_JointState *pData);
void PrintBase_JointTransform(const char *paramName, const asn1SccBase_JointTransform *pData);
void PrintBase_samples_DepthMap_PROJECTION_TYPE(const char *paramName, const asn1SccBase_samples_DepthMap_PROJECTION_TYPE *pData);
void PrintBase_Pose(const char *paramName, const asn1SccBase_Pose *pData);
void PrintWrappers_MatrixXd(const char *paramName, const asn1SccWrappers_MatrixXd *pData);
void PrintStd_orogen_typekits_mtype_std_vector_base_Trajectory(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_Trajectory *pData);
void PrintBase_samples_IMUSensors(const char *paramName, const asn1SccBase_samples_IMUSensors *pData);
void PrintBase_Pose2D(const char *paramName, const asn1SccBase_Pose2D *pData);
void PrintBase_samples_Pointcloud_m(const char *paramName, const asn1SccBase_samples_Pointcloud_m *pData);
void PrintBase_samples_RigidBodyState(const char *paramName, const asn1SccBase_samples_RigidBodyState *pData);
void PrintBase_samples_frame_frame_mode_t(const char *paramName, const asn1SccBase_samples_frame_frame_mode_t *pData);
void PrintBase_samples_LASER_RANGE_ERRORS(const char *paramName, const asn1SccBase_samples_LASER_RANGE_ERRORS *pData);
void PrintBase_NamedVector_Base_JointTransform(const char *paramName, const asn1SccBase_NamedVector_Base_JointTransform *pData);
void PrintWrappers_Matrix4d(const char *paramName, const asn1SccWrappers_Matrix4d *pData);
void PrintT_Time(const char *paramName, const asn1SccT_Time *pData);
void PrintWrappers_geometry_Spline(const char *paramName, const asn1SccWrappers_geometry_Spline *pData);
void PrintBase_Trajectory(const char *paramName, const asn1SccBase_Trajectory *pData);
void PrintWrappers_Vector4d(const char *paramName, const asn1SccWrappers_Vector4d *pData);
void PrintBase_samples_frame_frame_status_t(const char *paramName, const asn1SccBase_samples_frame_frame_status_t *pData);
void PrintDummyBase_T(const char *paramName, const asn1SccDummyBase_T *pData);
void PrintBase_commands_Motion2D(const char *paramName, const asn1SccBase_commands_Motion2D *pData);
void PrintBase_TransformWithCovariance(const char *paramName, const asn1SccBase_TransformWithCovariance *pData);
void PrintWrappers_Vector6d(const char *paramName, const asn1SccWrappers_Vector6d *pData);
void PrintWrappers_AngleAxisd(const char *paramName, const asn1SccWrappers_AngleAxisd *pData);
void PrintBase_NamedVector_Base_JointState(const char *paramName, const asn1SccBase_NamedVector_Base_JointState *pData);
void PrintBase_JointsTrajectory(const char *paramName, const asn1SccBase_JointsTrajectory *pData);
void PrintBase_Waypoint(const char *paramName, const asn1SccBase_Waypoint *pData);
void PrintBase_JointTrajectory(const char *paramName, const asn1SccBase_JointTrajectory *pData);
void PrintBase_samples_IMUSensors_m(const char *paramName, const asn1SccBase_samples_IMUSensors_m *pData);
void PrintBase_samples_BodyState(const char *paramName, const asn1SccBase_samples_BodyState *pData);
void PrintWrappers_VectorXd(const char *paramName, const asn1SccWrappers_VectorXd *pData);
void PrintDummy2Base_T(const char *paramName, const asn1SccDummy2Base_T *pData);
void PrintBase_JointState_MODE(const char *paramName, const asn1SccBase_JointState_MODE *pData);
void PrintBase_Trajectory_m(const char *paramName, const asn1SccBase_Trajectory_m *pData);
void PrintBase_commands_LinearAngular6DCommand_m(const char *paramName, const asn1SccBase_commands_LinearAngular6DCommand_m *pData);
void PrintBase_LinearAngular6DCommand(const char *paramName, const asn1SccBase_LinearAngular6DCommand *pData);
void PrintWrappers_Vector3d(const char *paramName, const asn1SccWrappers_Vector3d *pData);
void PrintBase_samples_Wrench_m(const char *paramName, const asn1SccBase_samples_Wrench_m *pData);
void PrintBase_samples_Sonar(const char *paramName, const asn1SccBase_samples_Sonar *pData);
void PrintBase_samples_DistanceImage(const char *paramName, const asn1SccBase_samples_DistanceImage *pData);
void PrintBase_Time(const char *paramName, const asn1SccBase_Time *pData);
void PrintBase_TwistWithCovariance_m(const char *paramName, const asn1SccBase_TwistWithCovariance_m *pData);
void PrintBase_geometry_SplineBase_CoordinateType(const char *paramName, const asn1SccBase_geometry_SplineBase_CoordinateType *pData);
void PrintT_Float(const char *paramName, const asn1SccT_Float *pData);
void PrintBase_samples_DepthMap(const char *paramName, const asn1SccBase_samples_DepthMap *pData);

#ifdef __cplusplus
}
#endif

#endif
