#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1Wrappers_Matrix3d(const char *paramName, const asn1SccWrappers_Matrix3d *pData);
void PrintASN1Base_NamedVector_base_Wrench_m(const char *paramName, const asn1SccBase_NamedVector_base_Wrench_m *pData);
void PrintASN1Base_TransformWithCovariance(const char *paramName, const asn1SccBase_TransformWithCovariance *pData);
void PrintASN1Base_Pose_m(const char *paramName, const asn1SccBase_Pose_m *pData);
void PrintASN1Base_Pose2D(const char *paramName, const asn1SccBase_Pose2D *pData);
void PrintASN1Base_Time_Resolution(const char *paramName, const asn1SccBase_Time_Resolution *pData);
void PrintASN1Wrappers_geometry_Spline(const char *paramName, const asn1SccWrappers_geometry_Spline *pData);
void PrintASN1Geometry_msgs_Point(const char *paramName, const asn1SccGeometry_msgs_Point *pData);
void PrintASN1Base_commands_Joints(const char *paramName, const asn1SccBase_commands_Joints *pData);
void PrintASN1Base_samples_frame_frame_status_t(const char *paramName, const asn1SccBase_samples_frame_frame_status_t *pData);
void PrintASN1Wrappers_Vector4d(const char *paramName, const asn1SccWrappers_Vector4d *pData);
void PrintASN1Wrappers_VectorXd(const char *paramName, const asn1SccWrappers_VectorXd *pData);
void PrintASN1Base_NamedVector_Base_JointLimitRange(const char *paramName, const asn1SccBase_NamedVector_Base_JointLimitRange *pData);
void PrintASN1T_Int16(const char *paramName, const asn1SccT_Int16 *pData);
void PrintASN1Base_samples_Pointcloud_m(const char *paramName, const asn1SccBase_samples_Pointcloud_m *pData);
void PrintASN1Std_orogen_typekits_mtype_std_vector_base_Trajectory(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_Trajectory *pData);
void PrintASN1Base_JointLimits(const char *paramName, const asn1SccBase_JointLimits *pData);
void PrintASN1Base_samples_BodyState(const char *paramName, const asn1SccBase_samples_BodyState *pData);
void PrintASN1Base_samples_RigidBodyState(const char *paramName, const asn1SccBase_samples_RigidBodyState *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintASN1Base_samples_RigidBodyAcceleration_m(const char *paramName, const asn1SccBase_samples_RigidBodyAcceleration_m *pData);
void PrintASN1Base_samples_SonarBeam(const char *paramName, const asn1SccBase_samples_SonarBeam *pData);
void PrintASN1Base_JointTransform_m(const char *paramName, const asn1SccBase_JointTransform_m *pData);
void PrintASN1Base_JointLimitRange(const char *paramName, const asn1SccBase_JointLimitRange *pData);
void PrintASN1Std_vector_Wrappers_Vector4d(const char *paramName, const asn1SccStd_vector_Wrappers_Vector4d *pData);
void PrintASN1T_Float(const char *paramName, const asn1SccT_Float *pData);
void PrintASN1Base_samples_Wrenches(const char *paramName, const asn1SccBase_samples_Wrenches *pData);
void PrintASN1Geometry_msgs_Point32(const char *paramName, const asn1SccGeometry_msgs_Point32 *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1Base_Pressure(const char *paramName, const asn1SccBase_Pressure *pData);
void PrintASN1Base_samples_DepthMap_DEPTH_MEASUREMENT_STATE(const char *paramName, const asn1SccBase_samples_DepthMap_DEPTH_MEASUREMENT_STATE *pData);
void PrintASN1Base_samples_Wrench(const char *paramName, const asn1SccBase_samples_Wrench *pData);
void PrintASN1Base_samples_LaserScan(const char *paramName, const asn1SccBase_samples_LaserScan *pData);
void PrintASN1Wrappers_MatrixXd(const char *paramName, const asn1SccWrappers_MatrixXd *pData);
void PrintASN1Base_samples_Pointcloud(const char *paramName, const asn1SccBase_samples_Pointcloud *pData);
void PrintASN1Base_samples_Wrench_m(const char *paramName, const asn1SccBase_samples_Wrench_m *pData);
void PrintASN1Wrappers_Vector2d(const char *paramName, const asn1SccWrappers_Vector2d *pData);
void PrintASN1Base_JointState_MODE(const char *paramName, const asn1SccBase_JointState_MODE *pData);
void PrintASN1Base_Trajectory_m(const char *paramName, const asn1SccBase_Trajectory_m *pData);
void PrintASN1Base_samples_Wrenches_m(const char *paramName, const asn1SccBase_samples_Wrenches_m *pData);
void PrintASN1Base_samples_IMUSensors(const char *paramName, const asn1SccBase_samples_IMUSensors *pData);
void PrintASN1Base_LinearAngular6DCommand(const char *paramName, const asn1SccBase_LinearAngular6DCommand *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_UInt64(const char *paramName, const asn1SccT_UInt64 *pData);
void PrintASN1Base_commands_LinearAngular6DCommand_m(const char *paramName, const asn1SccBase_commands_LinearAngular6DCommand_m *pData);
void PrintASN1Base_samples_Motion2D(const char *paramName, const asn1SccBase_samples_Motion2D *pData);
void PrintASN1Base_NamedVector_Base_JointTransform(const char *paramName, const asn1SccBase_NamedVector_Base_JointTransform *pData);
void PrintASN1Wrappers_Matrix2d(const char *paramName, const asn1SccWrappers_Matrix2d *pData);
void PrintASN1T_Time(const char *paramName, const asn1SccT_Time *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1Base_JointTransformVector(const char *paramName, const asn1SccBase_JointTransformVector *pData);
void PrintASN1Base_Temperature(const char *paramName, const asn1SccBase_Temperature *pData);
void PrintASN1Wrappers_Vector6d(const char *paramName, const asn1SccWrappers_Vector6d *pData);
void PrintASN1Wrappers_Matrix6d(const char *paramName, const asn1SccWrappers_Matrix6d *pData);
void PrintASN1Base_JointsTrajectory(const char *paramName, const asn1SccBase_JointsTrajectory *pData);
void PrintASN1Std_orogen_typekits_mtype_std_vector_base_Waypoint(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_Waypoint *pData);
void PrintASN1Base_samples_Sonar(const char *paramName, const asn1SccBase_samples_Sonar *pData);
void PrintASN1Base_Angle(const char *paramName, const asn1SccBase_Angle *pData);
void PrintASN1Base_samples_frame_frame_attrib_t(const char *paramName, const asn1SccBase_samples_frame_frame_attrib_t *pData);
void PrintASN1Base_geometry_SplineBase_CoordinateType(const char *paramName, const asn1SccBase_geometry_SplineBase_CoordinateType *pData);
void PrintASN1Base_samples_frame_Frame(const char *paramName, const asn1SccBase_samples_frame_Frame *pData);
void PrintASN1Base_PoseUpdateThreshold(const char *paramName, const asn1SccBase_PoseUpdateThreshold *pData);
void PrintASN1Base_TransformWithCovariance_m(const char *paramName, const asn1SccBase_TransformWithCovariance_m *pData);
void PrintASN1Wrappers_geometry_SplineType(const char *paramName, const asn1SccWrappers_geometry_SplineType *pData);
void PrintASN1Base_JointState(const char *paramName, const asn1SccBase_JointState *pData);
void PrintASN1Base_Pose2D_m(const char *paramName, const asn1SccBase_Pose2D_m *pData);
void PrintASN1Base_samples_frame_FramePair(const char *paramName, const asn1SccBase_samples_frame_FramePair *pData);
void PrintASN1Base_samples_RigidBodyAcceleration(const char *paramName, const asn1SccBase_samples_RigidBodyAcceleration *pData);
void PrintASN1Base_Wrench_m(const char *paramName, const asn1SccBase_Wrench_m *pData);
void PrintASN1T_Double(const char *paramName, const asn1SccT_Double *pData);
void PrintASN1Dummy2Base_T(const char *paramName, const asn1SccDummy2Base_T *pData);
void PrintASN1Base_TwistWithCovariance(const char *paramName, const asn1SccBase_TwistWithCovariance *pData);
void PrintASN1Base_NamedVector_Base_JointState(const char *paramName, const asn1SccBase_NamedVector_Base_JointState *pData);
void PrintASN1Base_TimeStamped_Base_commands_Motion2D(const char *paramName, const asn1SccBase_TimeStamped_Base_commands_Motion2D *pData);
void PrintASN1Base_samples_DepthMap_UNIT_AXIS(const char *paramName, const asn1SccBase_samples_DepthMap_UNIT_AXIS *pData);
void PrintASN1Base_samples_IMUSensors_m(const char *paramName, const asn1SccBase_samples_IMUSensors_m *pData);
void PrintASN1Base_NamedVector_Base_Wrench(const char *paramName, const asn1SccBase_NamedVector_Base_Wrench *pData);
void PrintASN1Base_samples_DepthMap_PROJECTION_TYPE(const char *paramName, const asn1SccBase_samples_DepthMap_PROJECTION_TYPE *pData);
void PrintASN1Base_Trajectory(const char *paramName, const asn1SccBase_Trajectory *pData);
void PrintASN1Base_Wrench(const char *paramName, const asn1SccBase_Wrench *pData);
void PrintASN1Base_samples_DepthMap(const char *paramName, const asn1SccBase_samples_DepthMap *pData);
void PrintASN1Base_TwistWithCovariance_m(const char *paramName, const asn1SccBase_TwistWithCovariance_m *pData);
void PrintASN1Base_samples_frame_frame_mode_t(const char *paramName, const asn1SccBase_samples_frame_frame_mode_t *pData);
void PrintASN1Wrappers_Quaterniond(const char *paramName, const asn1SccWrappers_Quaterniond *pData);
void PrintASN1Base_JointTransformVector_m(const char *paramName, const asn1SccBase_JointTransformVector_m *pData);
void PrintASN1Base_samples_BodyState_m(const char *paramName, const asn1SccBase_samples_BodyState_m *pData);
void PrintASN1Base_JointTransform(const char *paramName, const asn1SccBase_JointTransform *pData);
void PrintASN1Base_samples_frame_frame_size_t(const char *paramName, const asn1SccBase_samples_frame_frame_size_t *pData);
void PrintASN1Std_orogen_typekits_mtype_std_vector_base_Wrench(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_Wrench *pData);
void PrintASN1Base_NamedVector_Base_JointTrajectory(const char *paramName, const asn1SccBase_NamedVector_Base_JointTrajectory *pData);
void PrintASN1T_String(const char *paramName, const asn1SccT_String *pData);
void PrintASN1Base_JointTrajectory(const char *paramName, const asn1SccBase_JointTrajectory *pData);
void PrintASN1Wrappers_AngleAxisd(const char *paramName, const asn1SccWrappers_AngleAxisd *pData);
void PrintASN1Base_samples_SonarScan(const char *paramName, const asn1SccBase_samples_SonarScan *pData);
void PrintASN1Base_samples_DistanceImage(const char *paramName, const asn1SccBase_samples_DistanceImage *pData);
void PrintASN1Wrappers_Matrix4d(const char *paramName, const asn1SccWrappers_Matrix4d *pData);
void PrintASN1Base_Waypoint_m(const char *paramName, const asn1SccBase_Waypoint_m *pData);
void PrintASN1Base_samples_Pressure(const char *paramName, const asn1SccBase_samples_Pressure *pData);
void PrintASN1Base_NamedVector_base_JointTransform_m(const char *paramName, const asn1SccBase_NamedVector_base_JointTransform_m *pData);
void PrintASN1Std_orogen_typekits_mtype_std_vector_base_JointTransform(const char *paramName, const asn1SccStd_orogen_typekits_mtype_std_vector_base_JointTransform *pData);
void PrintASN1Base_Time(const char *paramName, const asn1SccBase_Time *pData);
void PrintASN1DummyBase_T(const char *paramName, const asn1SccDummyBase_T *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1Base_commands_Motion2D(const char *paramName, const asn1SccBase_commands_Motion2D *pData);
void PrintASN1T_UInt16(const char *paramName, const asn1SccT_UInt16 *pData);
void PrintASN1T_Int64(const char *paramName, const asn1SccT_Int64 *pData);
void PrintASN1Base_Waypoint(const char *paramName, const asn1SccBase_Waypoint *pData);
void PrintASN1Wrappers_Vector3d(const char *paramName, const asn1SccWrappers_Vector3d *pData);
void PrintASN1Base_Pose(const char *paramName, const asn1SccBase_Pose *pData);
void PrintASN1Base_samples_RigidBodyState_m(const char *paramName, const asn1SccBase_samples_RigidBodyState_m *pData);
void PrintASN1Base_samples_LASER_RANGE_ERRORS(const char *paramName, const asn1SccBase_samples_LASER_RANGE_ERRORS *pData);
void PrintASN1Base_commands_Speed6D(const char *paramName, const asn1SccBase_commands_Speed6D *pData);

#ifdef __cplusplus
}
#endif

#endif
