#if (defined (__PO_HI_NEED_DRIVER_1553_RASTA))\n
/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "1553.h"




flag __po_hi_c_Node_Addr_T_Equal(const __po_hi_c_Node_Addr_T* pVal1, const __po_hi_c_Node_Addr_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Node_Addr_T_Initialize(__po_hi_c_Node_Addr_T* pVal)
{

	(*(pVal)) = 0;
}

flag __po_hi_c_Node_Addr_T_IsConstraintValid(const __po_hi_c_Node_Addr_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((*(pVal)) <= 31UL);
    *pErrCode = ret ? 0 :  ERR_NODE_ADDR_T;

	return ret;
}



flag __po_hi_c_Standard_T_Equal(const __po_hi_c_Standard_T* pVal1, const __po_hi_c_Standard_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Standard_T_Initialize(__po_hi_c_Standard_T* pVal)
{

	(*(pVal)) = __po_hi_c_mil1553a;
}

flag __po_hi_c_Standard_T_IsConstraintValid(const __po_hi_c_Standard_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((((*(pVal)) == __po_hi_c_mil1553a)) || (((*(pVal)) == __po_hi_c_mil1553b)));
    *pErrCode = ret ? 0 :  ERR_STANDARD_T;

	return ret;
}



flag __po_hi_c_Mode_T_Equal(const __po_hi_c_Mode_T* pVal1, const __po_hi_c_Mode_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Mode_T_Initialize(__po_hi_c_Mode_T* pVal)
{

	(*(pVal)) = __po_hi_c_controller;
}

flag __po_hi_c_Mode_T_IsConstraintValid(const __po_hi_c_Mode_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((((((*(pVal)) == __po_hi_c_controller)) || (((*(pVal)) == __po_hi_c_terminal)))) || (((*(pVal)) == __po_hi_c_monitor)));
    *pErrCode = ret ? 0 :  ERR_MODE_T;

	return ret;
}



flag __po_hi_c_Bus_T_Equal(const __po_hi_c_Bus_T* pVal1, const __po_hi_c_Bus_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Bus_T_Initialize(__po_hi_c_Bus_T* pVal)
{

	(*(pVal)) = __po_hi_c_none;
}

flag __po_hi_c_Bus_T_IsConstraintValid(const __po_hi_c_Bus_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((((((((*(pVal)) == __po_hi_c_none)) || (((*(pVal)) == __po_hi_c_bus_a)))) || (((*(pVal)) == __po_hi_c_bus_b)))) || (((*(pVal)) == __po_hi_c_both)));
    *pErrCode = ret ? 0 :  ERR_BUS_T;

	return ret;
}



flag __po_hi_c_mil_1553_conf_t_devname_Equal(const __po_hi_c_mil_1553_conf_t_devname val1, const __po_hi_c_mil_1553_conf_t_devname val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_mil_1553_conf_t_Equal(const __po_hi_c_mil_1553_conf_t* pVal1, const __po_hi_c_mil_1553_conf_t* pVal2)
{
	flag ret=TRUE;

    ret = __po_hi_c_mil_1553_conf_t_devname_Equal(pVal1->devname, pVal2->devname);

    if (ret) {
        ret = (pVal1->standard == pVal2->standard);

        if (ret) {
            ret = (pVal1->mode == pVal2->mode);

            if (ret) {
                ret = (pVal1->bus == pVal2->bus);

                if (ret) {
                    ret = (pVal1->termaddr == pVal2->termaddr);

                    if (ret) {
                        ret = (pVal1->broadcast == pVal2->broadcast);

                        if (ret) {
                            ret = (pVal1->exist.rxblock == pVal2->exist.rxblock);
                            if (ret && pVal1->exist.rxblock) {
                            	ret = (pVal1->rxblock == pVal2->rxblock);
                            }

                            if (ret) {
                                ret = (pVal1->exist.txblock == pVal2->exist.txblock);
                                if (ret && pVal1->exist.txblock) {
                                	ret = (pVal1->txblock == pVal2->txblock);
                                }

                            }
                        }
                    }
                }
            }
        }
    }
	return ret;

}

void __po_hi_c_mil_1553_conf_t_devname_Initialize(__po_hi_c_mil_1553_conf_t_devname val)
{

	memset(val, 0x0, 21);

}
void __po_hi_c_mil_1553_conf_t_Initialize(__po_hi_c_mil_1553_conf_t* pVal)
{


	/*set devname */
	__po_hi_c_mil_1553_conf_t_devname_Initialize(pVal->devname);
	/*set standard */
	__po_hi_c_Standard_T_Initialize((&(pVal->standard)));
	/*set mode */
	__po_hi_c_Mode_T_Initialize((&(pVal->mode)));
	/*set bus */
	__po_hi_c_Bus_T_Initialize((&(pVal->bus)));
	/*set termaddr */
	__po_hi_c_Node_Addr_T_Initialize((&(pVal->termaddr)));
	/*set broadcast */
	pVal->broadcast = FALSE;
	/*set rxblock */
	pVal->exist.rxblock = 1;
	pVal->rxblock = FALSE;
	/*set txblock */
	pVal->exist.txblock = 1;
	pVal->txblock = FALSE;
}

flag __po_hi_c_mil_1553_conf_t_IsConstraintValid(const __po_hi_c_mil_1553_conf_t *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((1 <= strlen(pVal->devname)) && (strlen(pVal->devname) <= 20));
    *pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_DEVNAME;
    if (ret) {
        ret = (((pVal->standard == __po_hi_c_mil1553a)) || ((pVal->standard == __po_hi_c_mil1553b)));
        *pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_STANDARD;
        if (ret) {
            ret = (((((pVal->mode == __po_hi_c_controller)) || ((pVal->mode == __po_hi_c_terminal)))) || ((pVal->mode == __po_hi_c_monitor)));
            *pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_MODE;
            if (ret) {
                ret = (((((((pVal->bus == __po_hi_c_none)) || ((pVal->bus == __po_hi_c_bus_a)))) || ((pVal->bus == __po_hi_c_bus_b)))) || ((pVal->bus == __po_hi_c_both)));
                *pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_BUS;
                if (ret) {
                    ret = (pVal->termaddr <= 31UL);
                    *pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_TERMADDR;
                    if (ret) {
                        ret = TRUE;
                        *pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_BROADCAST;
                        if (ret) {
                            if (pVal->exist.rxblock) {
                            	ret = TRUE;
                            	*pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_RXBLOCK;
                            }
                            if (ret) {
                                if (pVal->exist.txblock) {
                                	ret = TRUE;
                                	*pErrCode = ret ? 0 :  ERR_MIL_1553_CONF_T_TXBLOCK;
                                }
                            }
                        }
                    }
                }
            }
        }
    }

	return ret;
}

\n#endif
