#if (defined (__PO_HI_NEED_DRIVER_SOCKETS) || defined (__PO_HI_NEED_DRIVER_RTEMS_NE2000_SOCKETS))\n
/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "ip.h"


const __po_hi_c_ip_conf_t localhost1 = {
    .devname = "eth0",
    .address = "127.0.0.1",
    .version = __po_hi_c_ipv4,
    .port = 5488,
    .exist = {
        .broadcast = 0,
        .netmask = 0,
        .gateway = 0,
        .dns = 0,
        .version = 0
    }
};
const __po_hi_c_ip_conf_t localhost2 = {
    .devname = "eth0",
    .address = "127.0.0.1",
    .version = __po_hi_c_ipv4,
    .port = 5489,
    .exist = {
        .broadcast = 0,
        .netmask = 0,
        .gateway = 0,
        .dns = 0,
        .version = 0
    }
};


flag __po_hi_c_Port_T_Equal(const __po_hi_c_Port_T* pVal1, const __po_hi_c_Port_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Port_T_Initialize(__po_hi_c_Port_T* pVal)
{

	(*(pVal)) = 0;
}

flag __po_hi_c_Port_T_IsConstraintValid(const __po_hi_c_Port_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((*(pVal)) <= 16535UL);
    *pErrCode = ret ? 0 :  ERR_PORT_T;

	return ret;
}



flag __po_hi_c_Version_T_Equal(const __po_hi_c_Version_T* pVal1, const __po_hi_c_Version_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Version_T_Initialize(__po_hi_c_Version_T* pVal)
{

	(*(pVal)) = __po_hi_c_ipv4;
}

flag __po_hi_c_Version_T_IsConstraintValid(const __po_hi_c_Version_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((((*(pVal)) == __po_hi_c_ipv4)) || (((*(pVal)) == __po_hi_c_ipv6)));
    *pErrCode = ret ? 0 :  ERR_VERSION_T;

	return ret;
}



flag __po_hi_c_ip_conf_t_devname_Equal(const __po_hi_c_ip_conf_t_devname val1, const __po_hi_c_ip_conf_t_devname val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_ip_conf_t_address_Equal(const __po_hi_c_ip_conf_t_address val1, const __po_hi_c_ip_conf_t_address val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_ip_conf_t_broadcast_Equal(const __po_hi_c_ip_conf_t_broadcast val1, const __po_hi_c_ip_conf_t_broadcast val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_ip_conf_t_netmask_Equal(const __po_hi_c_ip_conf_t_netmask val1, const __po_hi_c_ip_conf_t_netmask val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_ip_conf_t_gateway_Equal(const __po_hi_c_ip_conf_t_gateway val1, const __po_hi_c_ip_conf_t_gateway val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_ip_conf_t_dns_Equal(const __po_hi_c_ip_conf_t_dns val1, const __po_hi_c_ip_conf_t_dns val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_ip_conf_t_Equal(const __po_hi_c_ip_conf_t* pVal1, const __po_hi_c_ip_conf_t* pVal2)
{
	flag ret=TRUE;

    ret = __po_hi_c_ip_conf_t_devname_Equal(pVal1->devname, pVal2->devname);

    if (ret) {
        ret = __po_hi_c_ip_conf_t_address_Equal(pVal1->address, pVal2->address);

        if (ret) {
            ret = (pVal1->exist.broadcast == pVal2->exist.broadcast);
            if (ret && pVal1->exist.broadcast) {
            	ret = __po_hi_c_ip_conf_t_broadcast_Equal(pVal1->broadcast, pVal2->broadcast);
            }

            if (ret) {
                ret = (pVal1->exist.netmask == pVal2->exist.netmask);
                if (ret && pVal1->exist.netmask) {
                	ret = __po_hi_c_ip_conf_t_netmask_Equal(pVal1->netmask, pVal2->netmask);
                }

                if (ret) {
                    ret = (pVal1->exist.gateway == pVal2->exist.gateway);
                    if (ret && pVal1->exist.gateway) {
                    	ret = __po_hi_c_ip_conf_t_gateway_Equal(pVal1->gateway, pVal2->gateway);
                    }

                    if (ret) {
                        ret = (pVal1->exist.dns == pVal2->exist.dns);
                        if (ret && pVal1->exist.dns) {
                        	ret = __po_hi_c_ip_conf_t_dns_Equal(pVal1->dns, pVal2->dns);
                        }

                        if (ret) {
                            ret = (pVal1->exist.version == pVal2->exist.version);
                            if (ret && pVal1->exist.version) {
                            	ret = (pVal1->version == pVal2->version);
                            }

                            if (ret) {
                                ret = (pVal1->port == pVal2->port);

                            }
                        }
                    }
                }
            }
        }
    }
	return ret;

}

void __po_hi_c_ip_conf_t_devname_Initialize(__po_hi_c_ip_conf_t_devname val)
{

	memset(val, 0x0, 21);

}
void __po_hi_c_ip_conf_t_address_Initialize(__po_hi_c_ip_conf_t_address val)
{

	memset(val, 0x0, 41);

}
void __po_hi_c_ip_conf_t_broadcast_Initialize(__po_hi_c_ip_conf_t_broadcast val)
{

	memset(val, 0x0, 41);

}
void __po_hi_c_ip_conf_t_netmask_Initialize(__po_hi_c_ip_conf_t_netmask val)
{

	memset(val, 0x0, 41);

}
void __po_hi_c_ip_conf_t_gateway_Initialize(__po_hi_c_ip_conf_t_gateway val)
{

	memset(val, 0x0, 41);

}
void __po_hi_c_ip_conf_t_dns_Initialize(__po_hi_c_ip_conf_t_dns val)
{

	memset(val, 0x0, 41);

}
void __po_hi_c_ip_conf_t_Initialize(__po_hi_c_ip_conf_t* pVal)
{


	/*set devname */
	__po_hi_c_ip_conf_t_devname_Initialize(pVal->devname);
	/*set address */
	__po_hi_c_ip_conf_t_address_Initialize(pVal->address);
	/*set broadcast */
	pVal->exist.broadcast = 1;
	__po_hi_c_ip_conf_t_broadcast_Initialize(pVal->broadcast);
	/*set netmask */
	pVal->exist.netmask = 1;
	__po_hi_c_ip_conf_t_netmask_Initialize(pVal->netmask);
	/*set gateway */
	pVal->exist.gateway = 1;
	__po_hi_c_ip_conf_t_gateway_Initialize(pVal->gateway);
	/*set dns */
	pVal->exist.dns = 1;
	__po_hi_c_ip_conf_t_dns_Initialize(pVal->dns);
	/*set version */
	pVal->exist.version = 1;
	pVal->version = __po_hi_c_ipv4;
	/*set port */
	__po_hi_c_Port_T_Initialize((&(pVal->port)));
}

flag __po_hi_c_ip_conf_t_IsConstraintValid(const __po_hi_c_ip_conf_t *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((1 <= strlen(pVal->devname)) && (strlen(pVal->devname) <= 20));
    *pErrCode = ret ? 0 :  ERR_IP_CONF_T_DEVNAME;
    if (ret) {
        ret = ((1 <= strlen(pVal->address)) && (strlen(pVal->address) <= 40));
        *pErrCode = ret ? 0 :  ERR_IP_CONF_T_ADDRESS;
        if (ret) {
            if (pVal->exist.broadcast) {
            	ret = ((1 <= strlen(pVal->broadcast)) && (strlen(pVal->broadcast) <= 40));
            	*pErrCode = ret ? 0 :  ERR_IP_CONF_T_BROADCAST;
            }
            if (ret) {
                if (pVal->exist.netmask) {
                	ret = ((1 <= strlen(pVal->netmask)) && (strlen(pVal->netmask) <= 40));
                	*pErrCode = ret ? 0 :  ERR_IP_CONF_T_NETMASK;
                }
                if (ret) {
                    if (pVal->exist.gateway) {
                    	ret = ((1 <= strlen(pVal->gateway)) && (strlen(pVal->gateway) <= 40));
                    	*pErrCode = ret ? 0 :  ERR_IP_CONF_T_GATEWAY;
                    }
                    if (ret) {
                        if (pVal->exist.dns) {
                        	ret = ((1 <= strlen(pVal->dns)) && (strlen(pVal->dns) <= 40));
                        	*pErrCode = ret ? 0 :  ERR_IP_CONF_T_DNS;
                        }
                        if (ret) {
                            if (pVal->exist.version) {
                            	ret = (((pVal->version == __po_hi_c_ipv4)) || ((pVal->version == __po_hi_c_ipv6)));
                            	*pErrCode = ret ? 0 :  ERR_IP_CONF_T_VERSION;
                            }
                            if (ret) {
                                ret = (pVal->port <= 16535UL);
                                *pErrCode = ret ? 0 :  ERR_IP_CONF_T_PORT;
                            }
                        }
                    }
                }
            }
        }
    }

	return ret;
}

\n#endif
