#if (defined (__PO_HI_NEED_DRIVER_SPACEWIRE_RASTA))\n
/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "spacewire.h"


const __po_hi_c_spacewire_conf_t leon_rasta_spw_sender = {
    .devname = "/dev/grspwrasta0",
    .nodeaddr = 11,
    .use_router = FALSE,
    .exist = {
        .corefreq = 0,
        .clockdiv = 0,
        .use_router = 0,
        .remove_prot_id = 0,
        .rxblock = 0,
        .txblock = 0
    }
};
const __po_hi_c_spacewire_conf_t leon_rasta_spw_receiver = {
    .devname = "/dev/grspwrasta0",
    .nodeaddr = 22,
    .use_router = FALSE,
    .exist = {
        .corefreq = 0,
        .clockdiv = 0,
        .use_router = 0,
        .remove_prot_id = 0,
        .rxblock = 0,
        .txblock = 0
    }
};


flag __po_hi_c_Core_Frequence_T_Equal(const __po_hi_c_Core_Frequence_T* pVal1, const __po_hi_c_Core_Frequence_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Core_Frequence_T_Initialize(__po_hi_c_Core_Frequence_T* pVal)
{

	(*(pVal)) = 0;
}

flag __po_hi_c_Core_Frequence_T_IsConstraintValid(const __po_hi_c_Core_Frequence_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((*(pVal)) <= 4294967295UL);
    *pErrCode = ret ? 0 :  ERR_CORE_FREQUENCE_T;

	return ret;
}



flag __po_hi_c_Node_Addr_T_Equal(const __po_hi_c_Node_Addr_T* pVal1, const __po_hi_c_Node_Addr_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Node_Addr_T_Initialize(__po_hi_c_Node_Addr_T* pVal)
{

	(*(pVal)) = 0;
}

flag __po_hi_c_Node_Addr_T_IsConstraintValid(const __po_hi_c_Node_Addr_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_NODE_ADDR_T;

	return ret;
}



flag __po_hi_c_Clock_Division_T_Equal(const __po_hi_c_Clock_Division_T* pVal1, const __po_hi_c_Clock_Division_T* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

void __po_hi_c_Clock_Division_T_Initialize(__po_hi_c_Clock_Division_T* pVal)
{

	(*(pVal)) = 0;
}

flag __po_hi_c_Clock_Division_T_IsConstraintValid(const __po_hi_c_Clock_Division_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_CLOCK_DIVISION_T;

	return ret;
}



flag __po_hi_c_spacewire_conf_t_devname_Equal(const __po_hi_c_spacewire_conf_t_devname val1, const __po_hi_c_spacewire_conf_t_devname val2)
{
	return strcmp(val1, val2) == 0;

}

flag __po_hi_c_spacewire_conf_t_Equal(const __po_hi_c_spacewire_conf_t* pVal1, const __po_hi_c_spacewire_conf_t* pVal2)
{
	flag ret=TRUE;

    ret = __po_hi_c_spacewire_conf_t_devname_Equal(pVal1->devname, pVal2->devname);

    if (ret) {
        ret = (pVal1->nodeaddr == pVal2->nodeaddr);

        if (ret) {
            ret = (pVal1->exist.corefreq == pVal2->exist.corefreq);
            if (ret && pVal1->exist.corefreq) {
            	ret = (pVal1->corefreq == pVal2->corefreq);
            }

            if (ret) {
                ret = (pVal1->exist.clockdiv == pVal2->exist.clockdiv);
                if (ret && pVal1->exist.clockdiv) {
                	ret = (pVal1->clockdiv == pVal2->clockdiv);
                }

                if (ret) {
                    ret = (pVal1->exist.use_router == pVal2->exist.use_router);
                    if (ret && pVal1->exist.use_router) {
                    	ret = (pVal1->use_router == pVal2->use_router);
                    }

                    if (ret) {
                        ret = (pVal1->exist.remove_prot_id == pVal2->exist.remove_prot_id);
                        if (ret && pVal1->exist.remove_prot_id) {
                        	ret = (pVal1->remove_prot_id == pVal2->remove_prot_id);
                        }

                        if (ret) {
                            ret = (pVal1->exist.rxblock == pVal2->exist.rxblock);
                            if (ret && pVal1->exist.rxblock) {
                            	ret = (pVal1->rxblock == pVal2->rxblock);
                            }

                            if (ret) {
                                ret = (pVal1->exist.txblock == pVal2->exist.txblock);
                                if (ret && pVal1->exist.txblock) {
                                	ret = (pVal1->txblock == pVal2->txblock);
                                }

                            }
                        }
                    }
                }
            }
        }
    }
	return ret;

}

void __po_hi_c_spacewire_conf_t_devname_Initialize(__po_hi_c_spacewire_conf_t_devname val)
{

	memset(val, 0x0, 21);

}
void __po_hi_c_spacewire_conf_t_Initialize(__po_hi_c_spacewire_conf_t* pVal)
{


	/*set devname */
	__po_hi_c_spacewire_conf_t_devname_Initialize(pVal->devname);
	/*set nodeaddr */
	__po_hi_c_Node_Addr_T_Initialize((&(pVal->nodeaddr)));
	/*set corefreq */
	pVal->exist.corefreq = 1;
	__po_hi_c_Core_Frequence_T_Initialize((&(pVal->corefreq)));
	/*set clockdiv */
	pVal->exist.clockdiv = 1;
	__po_hi_c_Clock_Division_T_Initialize((&(pVal->clockdiv)));
	/*set use_router */
	pVal->exist.use_router = 1;
	pVal->use_router = FALSE;
	/*set remove_prot_id */
	pVal->exist.remove_prot_id = 1;
	pVal->remove_prot_id = FALSE;
	/*set rxblock */
	pVal->exist.rxblock = 1;
	pVal->rxblock = FALSE;
	/*set txblock */
	pVal->exist.txblock = 1;
	pVal->txblock = FALSE;
}

flag __po_hi_c_spacewire_conf_t_IsConstraintValid(const __po_hi_c_spacewire_conf_t *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((1 <= strlen(pVal->devname)) && (strlen(pVal->devname) <= 20));
    *pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_DEVNAME;
    if (ret) {
        ret = (pVal->nodeaddr <= 255UL);
        *pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_NODEADDR;
        if (ret) {
            if (pVal->exist.corefreq) {
            	ret = (pVal->corefreq <= 4294967295UL);
            	*pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_COREFREQ;
            }
            if (ret) {
                if (pVal->exist.clockdiv) {
                	ret = (pVal->clockdiv <= 255UL);
                	*pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_CLOCKDIV;
                }
                if (ret) {
                    if (pVal->exist.use_router) {
                    	ret = TRUE;
                    	*pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_USE_ROUTER;
                    }
                    if (ret) {
                        if (pVal->exist.remove_prot_id) {
                        	ret = TRUE;
                        	*pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_REMOVE_PROT_ID;
                        }
                        if (ret) {
                            if (pVal->exist.rxblock) {
                            	ret = TRUE;
                            	*pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_RXBLOCK;
                            }
                            if (ret) {
                                if (pVal->exist.txblock) {
                                	ret = TRUE;
                                	*pErrCode = ret ? 0 :  ERR_SPACEWIRE_CONF_T_TXBLOCK;
                                }
                            }
                        }
                    }
                }
            }
        }
    }

	return ret;
}

\n#endif
